# Generated by Django 4.2.3 on 2023-07-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['address']},
        ),
        migrations.AlterModelOptions(
            name='stockproduct',
            options={'ordering': ['stock', 'product']},
        ),
    ]
